name: base_bloc_3
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: 1.5.3
  easy_localization: 3.0.1
  get_it: 7.2.0
  flutter_bloc: 8.0.1
  dartz: 0.10.1
  retrofit: 3.3.1
  logger: 1.1.0

  copy_with_extension: 4.0.2
  freezed_annotation: 2.2.0
  json_annotation: 4.7.0
  dio: 4.0.6
  shared_preferences: 2.0.15
  cached_network_image: 3.2.1
  auto_route: 5.0.2
  firebase_core: 2.1.1
  firebase_messaging: 14.0.3
  flutter_local_notifications: 13.0.0
  connectivity_plus: 3.0.2
  flutter_dotenv: 5.0.2
  flutter_svg: 1.1.0
  #responsive
  flutter_screenutil: 5.5.3+2
  device_preview: 1.1.0
  flutter_gen: 5.1.0+1

  infinite_scroll_pagination: 3.2.0
  top_snackbar_flutter: 2.1.1
  equatable: 2.0.3
  shimmer: 2.0.0
  event_bus: 2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  freezed: 2.2.0
  injectable_generator: 1.5.4
  build_runner: 2.3.2
  json_serializable: 6.5.4
  retrofit_generator: 4.2.0
  auto_route_generator: 5.0.2
  copy_with_extension_gen: 4.0.2
  flutter_gen_runner: 5.1.0+1

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enable: true
    package_parameter_enabled: false

  font:
    enable: true


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/env/
    - assets/images/


