name: base_bloc_3
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  retrofit: ^3.0.1+1
  logger: ^1.1.0

  copy_with_extension: ^4.0.2
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  auto_route: ^4.0.1
  firebase_core: 1.17.1
  firebase_messaging: 11.4.0
  flutter_local_notifications: ^9.6.1
  connectivity_plus: ^2.3.4
  flutter_dotenv: ^5.0.2
  #responsive
  flutter_screenutil: ^5.5.3+2
  device_preview: ^1.1.0

  infinite_scroll_pagination: ^3.2.0

  top_snackbar_flutter: ^1.1.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  auto_route_generator: ^4.0.0
  copy_with_extension_gen: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/env/


